Offer `.nobuckcheck` when we fail to fetch from git.
Summary:
If a user updates their main repository, disconnects from the network,
then tries to build, buck will fail to update itself and refuse to build
anything, which is a safe default.

This diff adds an extra message to that path that tells the user that
that they can create a nobuckcheck file as a workaround.

Test Plan:
- Modified my buck repository to make the origin invalid.
- Changed the .buckversion file in my main repository.
- Attempted a build and saw

```
$ buck build fb4a
ssh: Could not resolve hostname invalid.facebook.com: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Failed to fetch Buck updates from git.
You can disable this by creating a '.nobuckcheck' file in your repository,
but this might lead to strange bugs or build failures.
```

diff --git a/bin/buck_common b/bin/buck_common
--- a/bin/buck_common
+++ b/bin/buck_common
@@ -1,5 +1,14 @@
 
 
+function gitFetchFailed()
+{
+  echo >&2
+  echo >&2 "Failed to fetch Buck updates from git."
+  echo >&2 "You can disable this by creating a '.nobuckcheck' file in your repository,"
+  echo >&2 "but this might lead to strange bugs or build failures."
+  exit 1
+}
+
 function checkForAnt()
 {
   if [ -z `command -v ant` ]; then
@@ -65,9 +74,9 @@ elif [ -e "${PROJECT_ROOT}/.buckversion" ]; then
   # If the hash is in not in the user's repository, do a `git fetch`.
   if ! git cat-file -e "$BUCK_REQUIRED_VERSION"; then
     if [ -e "${BUCK_REQUIRED_BRANCH}" ]; then
-      git fetch --all
+      git fetch --all || gitFetchFailed
     else
-      git fetch origin $BUCK_REQUIRED_BRANCH
+      git fetch origin $BUCK_REQUIRED_BRANCH || gitFetchFailed
     fi
   fi
 
