Fail buck_common if ant fails.
Test Plan: Broke the buck build, verified I got a error message

diff --git a/bin/buck_common b/bin/buck_common
--- a/bin/buck_common
+++ b/bin/buck_common
@@ -11,6 +11,19 @@ function checkForAnt()
   fi
 }
 
+function printAntFailedMessage()
+{
+    echo " :: 'ant' failed in the buck repo at $PWD."
+    if [ -d ".git" ]; then
+      echo " :: Try changing to that directory and running 'git clean -xfd'."
+    else
+      echo " :: Try changing to that directory and deleting the 'build' "
+      echo " :: directory."
+    fi
+    exit 1
+}
+
+
 # Set TMPDIR to a reasonable default if it isn't already set, so that mktmp(1) can be
 # succinctly and portably used.
 if [ "x${TMPDIR}" = "x" ] ; then
@@ -85,6 +98,9 @@ elif [ -e "${PROJECT_ROOT}/.buckversion" ]; then
     # Now that we have updated the repository, we should rebuild Buck.
     checkForAnt
     ant clean
+    if [ $? -ne 0 ]; then
+      printAntFailedMessage
+    fi
 
     # Rerun this script after checking out the new version.
     restartBuck $@
@@ -190,7 +206,13 @@ if [ ! -e "build/buck.jar" ]; then
   # Note the jar file will not be used,
   # but serves to represent whether everything has been built.
   checkForAnt
-  ant clean && ant
+  (
+    set -e
+    ant clean && ant
+  )
+  if [ $? -ne 0 ]; then
+    printAntFailedMessage
+  fi
 
   if [ $BUCKD_RUNNING -eq 0 ] && [ -e "${BUCK_BIN_DIRECTORY}/buckd" ]; then
     echo "Restarting buckd after building buck"
