Be reslient to an error being thrown on buckd's first start, which used to corrupt buckd.port.
Test Plan:
echo garbage > .buckd/buckd.port
buck build buck, verify it still works

diff --git a/bin/buck b/bin/buck
--- a/bin/buck
+++ b/bin/buck
@@ -39,19 +39,22 @@ if [ $BUCKD_RUNNING -eq 0 ] && [ -e "$BUCK_CLIENT" ]; then
     export BUCKD_COLOR_DEFAULT="never"
   fi
 
-  # Disable exit on error as exit code 2 is used to indicate the daemon is busy.
-  set +e
-  $BUCK_CLIENT --nailgun-port $BUCKD_PORT com.facebook.buck.cli.Main "$@"
-  BUCKD_STATUS=$?
-  set -e
+  if [[ ! $BUCKD_PORT =~ ^[0-9]+$ ]]; then
+    echo >&2 "Daemon port file is corrupt, starting new buck process."
+    killBuckd
+  else
+    # Disable exit on error as exit code 2 is used to indicate the daemon is busy.
+    set +e
+    $BUCK_CLIENT --nailgun-port $BUCKD_PORT com.facebook.buck.cli.Main "$@"
+    BUCKD_STATUS=$?
+    set -e
+    # If buck daemon is not busy, return exit code.
+    if [ $BUCKD_STATUS -ne 2 ]; then
+        exit $BUCKD_STATUS
+    fi
 
-  # If buck daemon is not busy, return exit code.
-  if [ $BUCKD_STATUS -ne 2 ]; then
-      exit $BUCKD_STATUS
+    echo >&2 "Daemon is busy, starting new buck process."
   fi
-
-  echo >&2 "Daemon is busy, starting new buck process."
-
 fi
 
 # Daemon is not running, or is busy so start buck process.
