Enforce serialization of command execution.
Summary:
Currently buckd allows multiple commands to be executed concurrently, which can lead to buckd
being left in an invalid state. This change enforces that only one command can be run at a time
to avoid those problems.

diff --git a/bin/buck b/bin/buck
--- a/bin/buck
+++ b/bin/buck
@@ -23,13 +23,27 @@ source "${BUCK_BIN_DIRECTORY}/buck_common"
 # If a buck daemon is running, use it.
 BUCK_CLIENT="${BUCK_DIRECTORY}/build/ng"
 if [ $BUCKD_RUNNING -eq 0 ] && [ -e "$BUCK_CLIENT" ]; then
+
+  echo "Using buckd."
+
   BUCKD_PORT=`cat ${BUCKD_DIR}/buckd.port`
-   $BUCK_CLIENT --nailgun-port $BUCKD_PORT \
-      com.facebook.buck.cli.Main "$@"
-  exit $?
+
+  # Disable exit on error as exit code 2 is used to indicate the daemon is busy.
+  set +e
+  $BUCK_CLIENT --nailgun-port $BUCKD_PORT com.facebook.buck.cli.Main "$@"
+  BUCKD_STATUS=$?
+  set -e
+
+  # If buck daemon is not busy, return exit code.
+  if [ $BUCKD_STATUS -ne 2 ]; then
+      exit $BUCKD_STATUS
+  fi
+
+  echo "Daemon is busy, starting new buck process."
+
 fi
 
-# Run buck.
+# Daemon is not running, or is busy so start buck process.
 java \
 $BUCK_JAVA_ARGS \
 -Dbuck.daemon=false \
