Run buckd by default if $USE_BUCKD is defined.
Test Plan:
buck build buck
yolo4

diff --git a/bin/buckd b/bin/buckd
--- a/bin/buckd
+++ b/bin/buckd
@@ -38,13 +38,13 @@ done
 
 # Use watchman if available.
 if command -v watchman &> /dev/null; then
-    echo "Using watchman."
+    echo >&2 "Using watchman."
     BUCK_JAVA_ARGS="$BUCK_JAVA_ARGS -Dbuck.buckd_watcher=Watchman"
     watchman watch $PROJECT_ROOT &> /dev/null
 else
-    echo "Watchman not found, please install when using buckd."
-    echo "See https://github.com/facebook/watchman for details."
-    echo "(brew install --HEAD watchman on OS X)"
+    echo >&2 "Watchman not found, please install when using buckd."
+    echo >&2 "See https://github.com/facebook/watchman for details."
+    echo >&2 "(brew install --HEAD watchman on OS X)"
     # Bail if watchman isn't installed as we know java's
     # FileSystemWatcher will take too long to process events.
     exit 0
